export const CONSTANTS = {

  HUERTO_LUGAR: 'lugar',
  HUERTO_CULTIVO: 'cultivo',

  HUERTO_LUGAR_H1: 'h1',
  HUERTO_LUGAR_H2: 'h2',
  HUERTO_LUGAR_H3: 'h3',
  HUERTO_LUGAR_H4: 'h4',

  HUERTO_CULTIVO_ZANAHORIA: 'zanahoria',
  HUERTO_CULTIVO_LECHUGA: 'lechuga',
  HUERTO_CULTIVO_CALABAZA: 'calabaza',
  HUERTO_CULTIVO_TIERRA: 'tierra'
} 