package models;

public enum ActionType {
	RESET_PRIVADO,
	ABRIR_INVENTARIO,
	CERRAR_INVENTARIO,
	AGREGAR_ELEMENTO_A_INVENTARIO,
	OBTENER_ELEMENTO_DE_INVENTARIO,
	ELIMINAR_ELEMENTOS_DE_INVENTARIO,
	ACCION,
	OBTENER_POSICION,
	CAMBIAR_PERSONAJE_MUJER,
	CAMBIAR_PERSONAJE_HOMBRE,
	MOVER_IZQUIERDA,
	GIRAR_IZQUIERDA,
	MOVER_DERECHA,
	GIRAR_DERECHA,
	MOVER_ARRIBA,
	GIRAR_ARRIBA,
	MOVER_ABAJO,
	GIRAR_ABAJO,
	COMPROBAR_CULTIVO,
	SEMBRAR,
	RECOLECTAR,
	APARECER_CULTIVO,
	DESAPARECER_CULTIVO,
	ENVIAR_MENSAJE
}
